name: Run Sentiment Trader Script

on:
  schedule:
    - cron: '30 14 * * 1-5'  # 14:30 UTC (adjust for your local time)
    - cron: '30 17 * * 1-5'  # 17:30 UTC
    - cron: '30 21 * * 1-5'  # 21:30 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
        run: python first_try.py
